package com.indianservers.universitynotifications;

import android.app.ProgressDialog;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.preference.PreferenceManager;
import android.support.v7.app.AlertDialog;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.SearchView;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.Button;
import android.widget.GridView;
import android.widget.TextView;
import android.widget.Toast;

import com.firebase.client.DataSnapshot;
import com.firebase.client.Firebase;
import com.firebase.client.FirebaseError;
import com.firebase.client.ValueEventListener;
import com.google.firebase.database.FirebaseDatabase;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.indianservers.universitynotifications.adapters.GridViewAdapter;
import com.indianservers.universitynotifications.classes.SubjectClass;

import java.lang.reflect.Array;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

public class RRBExamsActivity extends AppCompatActivity {
    private Firebase firebase;
    private GridView gridView;
    private ArrayList<SubjectClass> subjectClasses = new ArrayList<>();
    private GridViewAdapter gridViewAdapter;
    private ProgressDialog mProgressDialog;
    private AlertDialog alertDialog;
    private SharedPreferences settings;
    private SharedPreferences.Editor editor;
    private ArrayList<String> strings = new ArrayList<>();
    private String mode ,adapterposition;

    SearchView sv;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_rrbexams);
        Firebase.setAndroidContext(RRBExamsActivity.this);
        FirebaseDatabase.getInstance().setPersistenceEnabled(true);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        gridView = (GridView)findViewById(R.id.rrbonlineexamgridview);
        sv= (SearchView) findViewById(R.id.searchview);
        sv.setQueryHint("Select Subject");
        //SEARCHVIEW EVENTS
        mProgressDialog = new ProgressDialog(RRBExamsActivity.this);
        mProgressDialog.setMessage("Please Wait...");
        mProgressDialog.setCancelable(false);
        mProgressDialog.show();
        if(!isNetworkAvailable()){
            mProgressDialog.dismiss();
            Toast.makeText(RRBExamsActivity.this,"Check Your Internet Connection",Toast.LENGTH_LONG).show();
        }else {
            settings = PreferenceManager.getDefaultSharedPreferences(getApplicationContext());
            strings.add(" LANGUAGE PROCESSORS");
            strings.add("10A70105");
            strings.add("10A70107");
            strings.add("10A70302");
            strings.add("10A70303");
            strings.add("10A70305");
            strings.add("10A70406");
            strings.add("10A70407");
            strings.add("10A70506");
            strings.add("10A70509");
            strings.add("10A70801");
            strings.add("10A70802");
            strings.add("10A70803");
            strings.add("10A70804");
            strings.add("10A70805");
            strings.add("10A70807");
            strings.add("10A71001");
            strings.add("10A71002");
            strings.add("10A71003");
            strings.add("10A71004");
            strings.add("10A71005");
            strings.add("10A71006");
            strings.add("10A71102");
            strings.add("10A71103");
            strings.add("10A71104");
            strings.add("10A71106");
            strings.add("10A71202");
            strings.add("10A71205");
            strings.add("10A71207");
            strings.add("10A71208");
            strings.add("10A71209");
            strings.add("10A71901");
            strings.add("10A71904");
            strings.add("10A71906");
            strings.add("10A72101");
            strings.add("10A72102");
            strings.add("10A72203");
            strings.add("10A72204");
            strings.add("10A72205");
            strings.add("10A72206");
            strings.add("10A72301");
            strings.add("10A72302");
            strings.add("10A72303");
            strings.add("10A72304");
            strings.add("10A72308");
            strings.add("10A72401");
            strings.add("10A72403");
            strings.add("10A72404");
            strings.add("10A72405");
            strings.add("10A72406");
            strings.add("10A72601");
            strings.add("10A72602");
            strings.add("10A72603");
            strings.add("10A72604");
            strings.add("10A72607");
            strings.add("10A72702");
            strings.add("10A72703");
            strings.add("10A72704");
            strings.add("10A72707");
            strings.add("10A73101");
            strings.add("10A73103");
            strings.add("10A73104");
            strings.add("10A73105");
            strings.add("10A73107");
            strings.add("10A73110");
            strings.add("10A73111");
            strings.add("10A73112");
            strings.add("10A73113");
            strings.add("10A73114");
            strings.add("10A73115");
            strings.add("10A73117");
            strings.add("10A73118");
            strings.add("10A73120");
            strings.add("10A73121");
            strings.add("10A73122");
            strings.add("10A73128");
            strings.add("10A73130");
            strings.add("10A80101");
            strings.add("10A80102");
            strings.add("10A80103");
            strings.add("10A80104");
            strings.add("10A80105");
            strings.add("10A80106");
            strings.add("10A80108");
            strings.add("10A80109");
            strings.add("10A80110");
            strings.add("10A80201");
            strings.add("10A80202");
            strings.add("10A80203");
            strings.add("10A80204");
            strings.add("10A80205");
            strings.add("10A80206");
            strings.add("10A80207");
            strings.add("10A80208");
            strings.add("10A80209");
            strings.add("10A80210");
            strings.add("10A80301");
            strings.add("10A80303");
            strings.add("10A80304");
            strings.add("10A80305");
            strings.add("10A80306");
            strings.add("10A80307");
            strings.add("10A80308");
            strings.add("10A80311");
            strings.add("10A80313");
            strings.add("10A80401");
            strings.add("10A80402");
            strings.add("10A80403");
            strings.add("10A80404");
            strings.add("10A80405");
            strings.add("10A80406");
            strings.add("10A80407");
            strings.add("10A80408");
            strings.add("10A80410");
            strings.add("10A80501");
            strings.add("10A80502");
            strings.add("10A80503");
            strings.add("10A80504");
            strings.add("10A80505");
            strings.add("10A80506");
            strings.add("10A80507");
            strings.add("10A80508");
            strings.add("10A80509");
            strings.add("10A80510");
            strings.add("10A80511");
            strings.add("10A80512");
            strings.add("10A80514");
            strings.add("10A80516");
            strings.add("10A80801");
            strings.add("10A80804");
            strings.add("10A80805");
            strings.add("10A80806");
            strings.add("10A80807");
            strings.add("10A80808");
            strings.add("10A80810");
            strings.add("10A81001");
            strings.add("10A81002");
            strings.add("10A81004");
            strings.add("10A81005");
            strings.add("10A81006");
            strings.add("10A81101");
            strings.add("10A81103");
            strings.add("10A81104");
            strings.add("10A81106");
            strings.add("10A81107");
            strings.add("10A81109");
            strings.add("10A81201");
            strings.add("10A81202");
            strings.add("10A81203");
            strings.add("10A81204");
            strings.add("10A81901");
            strings.add("10A81904");
            strings.add("10A81905");
            strings.add("10A81906");
            strings.add("10A82101");
            strings.add("10A82102");
            strings.add("10A82103");
            strings.add("10A82106");
            strings.add("10A82109");
            strings.add("10A82304");
            strings.add("10A82305");
            strings.add("10A82306");
            strings.add("10A82308");
            strings.add("10A82401");
            strings.add("10A82404");
            strings.add("10A82406");
            strings.add("10A82407");
            strings.add("10A82601");
            strings.add("10A82610");
            strings.add("10A82706");
            strings.add("10A82707");
            strings.add("10B23002");
            strings.add("10B23004");
            strings.add("10B23005");
            strings.add("10B23006");
            strings.add("ADVANCED COMPUTER NETWORKS");
            strings.add("ADVANCED DATA STRUCTURES");
            strings.add("ADVANCED JAVA AND WEB TECHNOLOGIES");
            strings.add("ADVANCED JAVA PROGRAMMING");
            strings.add("AERODYNAMICS - I");
            strings.add("AEROSPACE MATERIALS AND COMPOSITES");
            strings.add("AEROSPACE PROPULSION - II");
            strings.add("AEROSPACE VEHICLE STRUCTURES - II");
            strings.add("AIRCRAFT PRODUCTION TECHNOLOGY");
            strings.add("ANALOG COMMUNICATIONS");
            strings.add("ANALYTICAL INSTRUMENTATION");
            strings.add("AUTOMOTIVE CHASSIS & SUSPENSION");
            strings.add("AUTOMOTIVE CHASSIS and SUSPENSION");
            strings.add("AUTOMOTIVE ELECTRICAL AND AUTOTRONICS");
            strings.add("AUTOMOTIVE ENGINES");
            strings.add("BASIC ELECTRICAL AND ELECTRONICS");
            strings.add("BASIC ELECTRONICS AND DEVICES");
            strings.add("BIO MEDICAL SIGNAL PROCESSING");
            strings.add("BIOCHEMICAL ENGINEERING");
            strings.add("BIOCHEMICAL REACTION ENGINEERING-II");
            strings.add("BIOINFORMATICS");
            strings.add("BIOLOGICAL CONTROL SYSTEMS");
            strings.add("BIOMEDICAL INSTRUMENTATION");
            strings.add("BUILDING MATERIALS AND CONSTRUCTION");
            strings.add("Biochemical Engineering");
            strings.add("C PROGRAMMING");
            strings.add("CHEMICAL ENGINEERING THERMODYNAMICS-I");
            strings.add("CHEMICAL PROCESS CALCULATIONS");
            strings.add("CHEMICAL REACTION ENGINEERING-II");
            strings.add("COMPLEX VARIABLES");
            strings.add("COMPLEX VARIABLES AND STATISTICAL METHOD");
            strings.add("COMPUTER ARCHITECTURE");
            strings.add("COMPUTER NETWORKS");
            strings.add("COMPUTER ORGANIZATION");
            strings.add("COMPUTER PROGRAMMING");
            strings.add("CONCRETE TECHNOLOGY");
            strings.add("CONTROL SYSTEMS");
            strings.add("CRYPTOGRAPHY AND NETWORK");
            strings.add("DATA ACQUISITION SYSTEMS");
            strings.add("DATA BASE MANAGEMENT SYSTEMS");
            strings.add("DATA STRUCTURES");
            strings.add("DATA WARE HOUSING AND DATA MINING");
            strings.add("DBMS");
            strings.add("DESIGN & DRAWING OF STEEL STRUCTURES");
            strings.add("DESIGN AND ANALYSIS OF ALGORITHMS");
            strings.add("DESIGN OF MACHINE MEMEBERS-II");
            strings.add("DEVELOPMENT OF MINERAL DEPOSITS");
            strings.add("DIGITAL IMAGE PROCESSING");
            strings.add("DIGITAL LOGIC DESIGN");
            strings.add("DIGITAL SIGNAL PROCESSING");
            strings.add("DISASTER MANAGEMENT");
            strings.add("ELECTRICAL CIRCUITS ANALYSIS-I");
            strings.add("ELECTRICAL DISTRIBUTION SYSTEMS");
            strings.add("ELECTRICAL MACHINE DESIGN");
            strings.add("ELECTRICAL MACHINES-I");
            strings.add("ELECTRICAL MACHINES-II");
            strings.add("ELECTRICAL SYSTEMS");
            strings.add("ELECTRICAL TECHNOLOGY");
            strings.add("ELECTRO MAGENETIC FIELDS");
            strings.add("ELECTRONIC CIRCUIT ANALYSIS");
            strings.add("ELECTRONIC DEVICES AND CIRCUITS");
            strings.add("ELEMENTS OF MECHANICAL ENGINEERING");
            strings.add("EM WAVES AND TRANSMISSION LINES");
            strings.add("EMBEDDED SYSTEMS");
            strings.add("ENGG CHEMISTRY");
            strings.add("ENGG MECHANICS ");
            strings.add("ENGG PHYSICS");
            strings.add("ENGINEERING CHEMISTRY");
            strings.add("ENGLISH-I");
            strings.add("ENGLISH-II");
            strings.add("ENVIRONMENTAL ENGINEERING");
            strings.add("ENVIRONMENTAL STUDIES");
            strings.add("Electrical Circuit Analysis-II");
            strings.add("Electronics");
            strings.add("FARM POWER AND TRACTOR SYSTEMS");
            strings.add("FLIGHT MECHANICS - II");
            strings.add("FLIGHT VEHICLE DESIGN");
            strings.add("FLUID MECHANICS & HYDRAULIC MACHINERY");
            strings.add("FLUID MECHANICS AND OPEN CHANNEL HYDRAULICS");
            strings.add("FORMAL LANGUAGES AND AUTOMATA THEORY");
            strings.add("Fluid Mechanics");
            strings.add("GENERAL GEOLOGY");
            strings.add("GEOTECHNICAL ENGINEERING - I");
            strings.add("GEOTECHNICAL ENGINEERING-II");
            strings.add("GROUND IMPROVEMENT TECHNNIQUES");
            strings.add("GROUND WATER HYDROLOGY");
            strings.add("HEAT AND MASS TRANSFER");
            strings.add("HEAT TRANSFER");
            strings.add("HIGH VOLTAGE ENGINEERING");
            strings.add("HYDRAULICS AND HYDRAULIC MACHINERY");
            strings.add("IC ENGINES & GAS TURBINES");
            strings.add("IMMUNOLOGY");
            strings.add("INDUSTRIAL ENGG & MANAGEMENT");
            strings.add("INDUSTRIAL ENGG and MANAGEMENT");
            strings.add("INDUSTRIAL MANAGEMENT");
            strings.add("INORGANIC CHEMICAL TECHNOLOGY");
            strings.add("INSTRUMENTATION");
            strings.add("INSTRUMENTATION & CONTROL SYSTEMS");
            strings.add("INSTRUMENTATION AND BIO PROCESS CONTROL");
            strings.add("INSTRUMENTATION and CONTROL SYSTEMS");
            strings.add("INTRODUCTION TO SPACE TECHNOLOGY");
            strings.add("JAVA PROGRAMMING");
            strings.add("KINEMATICS OF MACHINERY");
            strings.add("LASERS AND FIBER OPTICS IN MEDICINE");
            strings.add("MACHINE TOOLS & METROLOGY");
            strings.add("MACHINE TOOLS and METROLOGY");
            strings.add("MANAGEMENT SCIENCE");
            strings.add("MANAGERIAL ECONOMICS & FINANCIAL ANALYSIS");
            strings.add("MANAGERIAL ECONOMICS AND FINANCIAL ANALYSIS");
            strings.add("MASS TRANSFER OPERATIONS - II");
            strings.add("MATERIAL ENGINEERING");
            strings.add("MATHEMATICAL FOUNDATIONS OF COMPUTER SCIENCE");
            strings.add("MATHEMATICS-I");
            strings.add("MATHEMATICS-II");
            strings.add("MATHEMATICS-II (MM)");
            strings.add("MATHEMATICS-III");
            strings.add("MBA");
            strings.add("MECHANICAL UNIT OPERATIONS");
            strings.add("MECHANICS OF FLUIDS");
            strings.add("MECHANICS OF SOLIDS");
            strings.add("MECHANISMS AND MECHANICAL DESIGN");
            strings.add("MEDICAL IMAGING TECHNIQUES");
            strings.add("MEMS");
            strings.add("METALLURGY & MATERIALS SCIENCE");
            strings.add("METROLOGY");
            strings.add("MICROPROCESSORS & MICROCONTROLLERS");
            strings.add("MICROPROCESSORS AND MICROCONTROLLERS");
            strings.add("MICROWAVE ENGINEERING");
            strings.add("MINE ENVIRONMENT ENGINEERING - II");
            strings.add("MINE STYSTEMS ENGINEERING");
            strings.add("MINE SURVEYING -I");
            strings.add("MINERAL ENGINEERING AND FUEL TECHNOLOGY");
            strings.add("MINING GEOLOGY - II");
            strings.add("MINING GEOLOGY- I");
            strings.add("MINING MACHINERY");
            strings.add("MOBILE COMPUTING");
            strings.add("MOMENTUM TRANSFER");
            strings.add("Metallurgy");
            strings.add("Metallurgy & Materials Science");
            strings.add("Mining Technology");
            strings.add("NATURAL GAS ENGINEERING");
            strings.add("NETWORK ANALYSIS");
            strings.add("OBJECT ORIENTED ANALYSIS AND DESIGN");
            strings.add("OBJECT ORIENTED PROGRAMMING");
            strings.add("OOPS THROUGH C++");
            strings.add("OPEN SORUCE SOFTWARE");
            strings.add("OPERATING SYSTEMS");
            strings.add("OPTICAL COMMUNICATIONS");
            strings.add("ORGANIC CHEMISTRY");
            strings.add("Operations Research");
            strings.add("P AND S");
            strings.add("PETROLEUM GEOLOGY");
            strings.add("PETROLEUM INDUSTRY MANAGEMENT");
            strings.add("PETROLEUM PRODUCTION ENGINEERING");
            strings.add("PETROLEUM RESERVOIR ENGINEERING");
            strings.add("PHYSICAL CHEMISTRY");
            strings.add("PHYSICAL METALLURGY");
            strings.add("POWER SEMICONDUCTOR DRIVES");
            strings.add("POWER SYSTEM ANALYSIS");
            strings.add("POWER SYSTEM OPERATION and CONTROL");
            strings.add("POWER SYSTEMS-I");
            strings.add("PRINCIPLES OF COMMUNICATION");
            strings.add("PRINCIPLES OF SOIL SCIENCE AND AGRONOMY");
            strings.add("PROBABILITY AND STATISTICS");
            strings.add("PROCESS DYNAMICS & CONTROL");
            strings.add("PROCESS DYNAMICS and CONTROL");
            strings.add("PROCESS ENGINEERING ECONOMICS");
            strings.add("PROCESS HEAT TRANSFER");
            strings.add("PRODUCT DESIGN AND ASSEMBLY AUTOMATION");
            strings.add("PRODUCTION TECHNOLOGY");
            strings.add("PROFESSIONAL ETHICS and HUMAN VALUES");
            strings.add("PROPERTIES AND STRENGTH OF MATERIALS");
            strings.add("PULSE & DIGITAL CIRCUITS");
            strings.add("Petroleum Engineering");
            strings.add("Professional Ethics and Human Values");
            strings.add("RADAR SYSTEMS");
            strings.add("RANDOM VARIABLES and STOCHASTIC PROCESSES");
            strings.add("REFRIGERATION ");
            strings.add("REMOTE SENSING AND GIS APPLICATION");
            strings.add("RENEWABLE ENERGY SOURCES");
            strings.add("ROBOTICS");
            strings.add("SIGNAL CONDITIONING");
            strings.add("SOFTWARE ENGINEERING");
            strings.add("SOFTWARE PROJECT MANAGEMENT");
            strings.add("SOIL MECHANICS");
            strings.add("STRENGTH OF MATERIALS");
            strings.add("STRENGTH OF MATERIALS- II");
            strings.add("STRUCTURAL ANALYSIS");
            strings.add("STRUCTURE AND ORGANIZATION OF TISSUES");
            strings.add("SURFACE MINING");
            strings.add("SURFACE PRODUCTION OPERATIONS");
            strings.add("SURFACE WATER HYDROLOGY");
            strings.add("SURVEYING");
            strings.add("SURVEYING AND OFFSHORE STRUCTURES");
            strings.add("SWITCH GEAR & PROTECTION");
            strings.add("SWITCHING THEORY AND LOGIC DESIGN");
            strings.add("SYSTEM MODELING AND SIMULATION");
            strings.add("TELECOMMUNICATION SWITCHING SYSTEMS");
            strings.add("THEORY OF MACHINES");
            strings.add("THERMAL ENGINEERING -I");
            strings.add("THERMAL ENGINEERING FOR MINING");
            strings.add("THERMODYNAMICS");
            strings.add("THERMODYNAMICS & KINETICS");
            strings.add("THERMODYNAMICS FOR PETROLEUM ENGINEERS");
            strings.add("TRANSDUCER TECHNOLOGY");
            strings.add("TRANSPORT PHENOMENA IN BIO PROCESSES");
            strings.add("TRANSPORTATION ENGINEERING - II");
            strings.add("Thermal & Hydro Prime Movers");
            strings.add("UML & DESIGN PATTERNS");
            strings.add("UNCONVENTIONAL MACHINING PROCESSES");
            strings.add("UNDER GROUND METAL MINING TECHNOLOGY");
            strings.add("UNIX PROGRAMMING");
            strings.add("UTILIZATION OF ELECTRICAL ENERGY");
            strings.add("VEHICLE TRANSPORT MANAGEMENT");
            strings.add("VLSI DESIGN");
            strings.add("WATER AND WASTEWATER ENGINEERING");
            strings.add("WATER RESOURCES ENGINEERING - II");
            strings.add("WELL COMPLETIONS & TESTING");
            strings.add("WELL COMPLETIONS and TESTING");
            mProgressDialog.dismiss();
            gridViewAdapter = new GridViewAdapter(RRBExamsActivity.this,strings);
            gridView.setAdapter(gridViewAdapter);
            sv.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
                @Override
                public boolean onQueryTextSubmit(String query) {
                    return false;
                }

                @Override
                public boolean onQueryTextChange(String newText) {
                    //SEARCH FILTER
                    gridViewAdapter.filter(newText);

                    return false;
                }
            });
            gridView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                    final String type = ((TextView)view.findViewById(R.id.textView)).getText().toString();

                    final AlertDialog.Builder builder = new AlertDialog.Builder(RRBExamsActivity.this);
                    LayoutInflater inflater = RRBExamsActivity.this.getLayoutInflater();
                    final View dialogView = inflater.inflate(R.layout.modeofexam, null);
                    builder.setView(dialogView);
                    alertDialog = builder.create();
                    alertDialog.show();
                    Button practice = (Button)dialogView.findViewById(R.id.practice);
                    practice.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View v) {
                            mode = "practice";
                            editor = settings.edit();
                            editor.putString("exammode",mode);
                            editor.commit();
                            Intent intent1 = new Intent(RRBExamsActivity.this,Quiz.class);
                            intent1.putExtra("subname",type);
                            startActivity(intent1);
                            alertDialog.dismiss();
                        }
                    });
                    Button test =(Button)dialogView.findViewById(R.id.test);
                    test.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View v) {
                            mode = "test";
                            editor = settings.edit();
                            editor.putString("exammode",mode);
                            editor.commit();
                            Intent intent1 = new Intent(RRBExamsActivity.this,Quiz.class);
                            intent1.putExtra("subname",type);
                            startActivity(intent1);
                            alertDialog.dismiss();
                        }
                    });
                }
            });
        }

    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()){
            case android.R.id.home:
                this.finish();
                break;
        }
        return super.onOptionsItemSelected(item);
    }
    private boolean isNetworkAvailable() {
        ConnectivityManager connectivityManager
                = (ConnectivityManager) getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkInfo activeNetworkInfo = connectivityManager.getActiveNetworkInfo();
        return activeNetworkInfo != null && activeNetworkInfo.isConnected();
    }
}
