package com.indianservers.universitynotifications;

import android.app.ProgressDialog;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.preference.PreferenceManager;
import android.support.v7.app.AlertDialog;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.SearchView;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.Button;
import android.widget.GridView;
import android.widget.TextView;
import android.widget.Toast;

import com.firebase.client.DataSnapshot;
import com.firebase.client.Firebase;
import com.firebase.client.FirebaseError;
import com.firebase.client.ValueEventListener;
import com.google.firebase.database.FirebaseDatabase;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.indianservers.universitynotifications.adapters.GridViewAdapter;
import com.indianservers.universitynotifications.classes.SubjectClass;

import java.lang.reflect.Array;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

public class RRBExamsActivity extends AppCompatActivity {
    private Firebase firebase;
    private GridView gridView;
    private ArrayList<SubjectClass> subjectClasses = new ArrayList<>();
    private GridViewAdapter gridViewAdapter;
    private ProgressDialog mProgressDialog;
    private AlertDialog alertDialog;
    private SharedPreferences settings;
    private SharedPreferences.Editor editor;
    private ArrayList<String> strings = new ArrayList<>();
    private String mode ,adapterposition;
    private SearchView sv;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_rrbexams);
        Firebase.setAndroidContext(RRBExamsActivity.this);
        FirebaseDatabase.getInstance().setPersistenceEnabled(true);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        gridView = (GridView)findViewById(R.id.rrbonlineexamgridview);
        sv= (SearchView) findViewById(R.id.searchview);
        //SEARCHVIEW EVENTS
        mProgressDialog = new ProgressDialog(RRBExamsActivity.this);
        mProgressDialog.setMessage("Please Wait...");
        mProgressDialog.setCancelable(false);
        mProgressDialog.show();
        if(!isNetworkAvailable()){
            mProgressDialog.dismiss();
            Toast.makeText(RRBExamsActivity.this,"Check Your Internet Connection",Toast.LENGTH_LONG).show();
        }else {
            settings = PreferenceManager.getDefaultSharedPreferences(getApplicationContext());
            subjectClasses.add(new SubjectClass(" LANGUAGE PROCESSORS"));
            subjectClasses.add(new SubjectClass("10A70105"));
            subjectClasses.add(new SubjectClass("10A70107"));
            subjectClasses.add(new SubjectClass("10A70302"));
            subjectClasses.add(new SubjectClass("10A70303"));
            subjectClasses.add(new SubjectClass("10A70305"));
            subjectClasses.add(new SubjectClass("10A70406"));
            subjectClasses.add(new SubjectClass("10A70407"));
            subjectClasses.add(new SubjectClass("10A70506"));
            subjectClasses.add(new SubjectClass("10A70509"));
            subjectClasses.add(new SubjectClass("10A70801"));
            subjectClasses.add(new SubjectClass("10A70802"));
            subjectClasses.add(new SubjectClass("10A70803"));
            subjectClasses.add(new SubjectClass("10A70804"));
            subjectClasses.add(new SubjectClass("10A70805"));
            subjectClasses.add(new SubjectClass("10A70807"));
            subjectClasses.add(new SubjectClass("10A71001"));
            subjectClasses.add(new SubjectClass("10A71002"));
            subjectClasses.add(new SubjectClass("10A71003"));
            subjectClasses.add(new SubjectClass("10A71004"));
            subjectClasses.add(new SubjectClass("10A71005"));
            subjectClasses.add(new SubjectClass("10A71006"));
            subjectClasses.add(new SubjectClass("10A71102"));
            subjectClasses.add(new SubjectClass("10A71103"));
            subjectClasses.add(new SubjectClass("10A71104"));
            subjectClasses.add(new SubjectClass("10A71106"));
            subjectClasses.add(new SubjectClass("10A71202"));
            subjectClasses.add(new SubjectClass("10A71205"));
            subjectClasses.add(new SubjectClass("10A71207"));
            subjectClasses.add(new SubjectClass("10A71208"));
            subjectClasses.add(new SubjectClass("10A71209"));
            subjectClasses.add(new SubjectClass("10A71901"));
            subjectClasses.add(new SubjectClass("10A71904"));
            subjectClasses.add(new SubjectClass("10A71906"));
            subjectClasses.add(new SubjectClass("10A72101"));
            subjectClasses.add(new SubjectClass("10A72102"));
            subjectClasses.add(new SubjectClass("10A72203"));
            subjectClasses.add(new SubjectClass("10A72204"));
            subjectClasses.add(new SubjectClass("10A72205"));
            subjectClasses.add(new SubjectClass("10A72206"));
            subjectClasses.add(new SubjectClass("10A72301"));
            subjectClasses.add(new SubjectClass("10A72302"));
            subjectClasses.add(new SubjectClass("10A72303"));
            subjectClasses.add(new SubjectClass("10A72304"));
            subjectClasses.add(new SubjectClass("10A72308"));
            subjectClasses.add(new SubjectClass("10A72401"));
            subjectClasses.add(new SubjectClass("10A72403"));
            subjectClasses.add(new SubjectClass("10A72404"));
            subjectClasses.add(new SubjectClass("10A72405"));
            subjectClasses.add(new SubjectClass("10A72406"));
            subjectClasses.add(new SubjectClass("10A72601"));
            subjectClasses.add(new SubjectClass("10A72602"));
            subjectClasses.add(new SubjectClass("10A72603"));
            subjectClasses.add(new SubjectClass("10A72604"));
            subjectClasses.add(new SubjectClass("10A72607"));
            subjectClasses.add(new SubjectClass("10A72702"));
            subjectClasses.add(new SubjectClass("10A72703"));
            subjectClasses.add(new SubjectClass("10A72704"));
            subjectClasses.add(new SubjectClass("10A72707"));
            subjectClasses.add(new SubjectClass("10A73101"));
            subjectClasses.add(new SubjectClass("10A73103"));
            subjectClasses.add(new SubjectClass("10A73104"));
            subjectClasses.add(new SubjectClass("10A73105"));
            subjectClasses.add(new SubjectClass("10A73107"));
            subjectClasses.add(new SubjectClass("10A73110"));
            subjectClasses.add(new SubjectClass("10A73111"));
            subjectClasses.add(new SubjectClass("10A73112"));
            subjectClasses.add(new SubjectClass("10A73113"));
            subjectClasses.add(new SubjectClass("10A73114"));
            subjectClasses.add(new SubjectClass("10A73115"));
            subjectClasses.add(new SubjectClass("10A73117"));
            subjectClasses.add(new SubjectClass("10A73118"));
            subjectClasses.add(new SubjectClass("10A73120"));
            subjectClasses.add(new SubjectClass("10A73121"));
            subjectClasses.add(new SubjectClass("10A73122"));
            subjectClasses.add(new SubjectClass("10A73128"));
            subjectClasses.add(new SubjectClass("10A73130"));
            subjectClasses.add(new SubjectClass("10A80101"));
            subjectClasses.add(new SubjectClass("10A80102"));
            subjectClasses.add(new SubjectClass("10A80103"));
            subjectClasses.add(new SubjectClass("10A80104"));
            subjectClasses.add(new SubjectClass("10A80105"));
            subjectClasses.add(new SubjectClass("10A80106"));
            subjectClasses.add(new SubjectClass("10A80108"));
            subjectClasses.add(new SubjectClass("10A80109"));
            subjectClasses.add(new SubjectClass("10A80110"));
            subjectClasses.add(new SubjectClass("10A80201"));
            subjectClasses.add(new SubjectClass("10A80202"));
            subjectClasses.add(new SubjectClass("10A80203"));
            subjectClasses.add(new SubjectClass("10A80204"));
            subjectClasses.add(new SubjectClass("10A80205"));
            subjectClasses.add(new SubjectClass("10A80206"));
            subjectClasses.add(new SubjectClass("10A80207"));
            subjectClasses.add(new SubjectClass("10A80208"));
            subjectClasses.add(new SubjectClass("10A80209"));
            subjectClasses.add(new SubjectClass("10A80210"));
            subjectClasses.add(new SubjectClass("10A80301"));
            subjectClasses.add(new SubjectClass("10A80303"));
            subjectClasses.add(new SubjectClass("10A80304"));
            subjectClasses.add(new SubjectClass("10A80305"));
            subjectClasses.add(new SubjectClass("10A80306"));
            subjectClasses.add(new SubjectClass("10A80307"));
            subjectClasses.add(new SubjectClass("10A80308"));
            subjectClasses.add(new SubjectClass("10A80311"));
            subjectClasses.add(new SubjectClass("10A80313"));
            subjectClasses.add(new SubjectClass("10A80401"));
            subjectClasses.add(new SubjectClass("10A80402"));
            subjectClasses.add(new SubjectClass("10A80403"));
            subjectClasses.add(new SubjectClass("10A80404"));
            subjectClasses.add(new SubjectClass("10A80405"));
            subjectClasses.add(new SubjectClass("10A80406"));
            subjectClasses.add(new SubjectClass("10A80407"));
            subjectClasses.add(new SubjectClass("10A80408"));
            subjectClasses.add(new SubjectClass("10A80410"));
            subjectClasses.add(new SubjectClass("10A80501"));
            subjectClasses.add(new SubjectClass("10A80502"));
            subjectClasses.add(new SubjectClass("10A80503"));
            subjectClasses.add(new SubjectClass("10A80504"));
            subjectClasses.add(new SubjectClass("10A80505"));
            subjectClasses.add(new SubjectClass("10A80506"));
            subjectClasses.add(new SubjectClass("10A80507"));
            subjectClasses.add(new SubjectClass("10A80508"));
            subjectClasses.add(new SubjectClass("10A80509"));
            subjectClasses.add(new SubjectClass("10A80510"));
            subjectClasses.add(new SubjectClass("10A80511"));
            subjectClasses.add(new SubjectClass("10A80512"));
            subjectClasses.add(new SubjectClass("10A80514"));
            subjectClasses.add(new SubjectClass("10A80516"));
            subjectClasses.add(new SubjectClass("10A80801"));
            subjectClasses.add(new SubjectClass("10A80804"));
            subjectClasses.add(new SubjectClass("10A80805"));
            subjectClasses.add(new SubjectClass("10A80806"));
            subjectClasses.add(new SubjectClass("10A80807"));
            subjectClasses.add(new SubjectClass("10A80808"));
            subjectClasses.add(new SubjectClass("10A80810"));
            subjectClasses.add(new SubjectClass("10A81001"));
            subjectClasses.add(new SubjectClass("10A81002"));
            subjectClasses.add(new SubjectClass("10A81004"));
            subjectClasses.add(new SubjectClass("10A81005"));
            subjectClasses.add(new SubjectClass("10A81006"));
            subjectClasses.add(new SubjectClass("10A81101"));
            subjectClasses.add(new SubjectClass("10A81103"));
            subjectClasses.add(new SubjectClass("10A81104"));
            subjectClasses.add(new SubjectClass("10A81106"));
            subjectClasses.add(new SubjectClass("10A81107"));
            subjectClasses.add(new SubjectClass("10A81109"));
            subjectClasses.add(new SubjectClass("10A81201"));
            subjectClasses.add(new SubjectClass("10A81202"));
            subjectClasses.add(new SubjectClass("10A81203"));
            subjectClasses.add(new SubjectClass("10A81204"));
            subjectClasses.add(new SubjectClass("10A81901"));
            subjectClasses.add(new SubjectClass("10A81904"));
            subjectClasses.add(new SubjectClass("10A81905"));
            subjectClasses.add(new SubjectClass("10A81906"));
            subjectClasses.add(new SubjectClass("10A82101"));
            subjectClasses.add(new SubjectClass("10A82102"));
            subjectClasses.add(new SubjectClass("10A82103"));
            subjectClasses.add(new SubjectClass("10A82106"));
            subjectClasses.add(new SubjectClass("10A82109"));
            subjectClasses.add(new SubjectClass("10A82304"));
            subjectClasses.add(new SubjectClass("10A82305"));
            subjectClasses.add(new SubjectClass("10A82306"));
            subjectClasses.add(new SubjectClass("10A82308"));
            subjectClasses.add(new SubjectClass("10A82401"));
            subjectClasses.add(new SubjectClass("10A82404"));
            subjectClasses.add(new SubjectClass("10A82406"));
            subjectClasses.add(new SubjectClass("10A82407"));
            subjectClasses.add(new SubjectClass("10A82601"));
            subjectClasses.add(new SubjectClass("10A82610"));
            subjectClasses.add(new SubjectClass("10A82706"));
            subjectClasses.add(new SubjectClass("10A82707"));
            subjectClasses.add(new SubjectClass("10B23002"));
            subjectClasses.add(new SubjectClass("10B23004"));
            subjectClasses.add(new SubjectClass("10B23005"));
            subjectClasses.add(new SubjectClass("10B23006"));
            subjectClasses.add(new SubjectClass("ADVANCED COMPUTER NETWORKS"));
            subjectClasses.add(new SubjectClass("ADVANCED DATA STRUCTURES"));
            subjectClasses.add(new SubjectClass("ADVANCED JAVA AND WEB TECHNOLOGIES"));
            subjectClasses.add(new SubjectClass("ADVANCED JAVA PROGRAMMING"));
            subjectClasses.add(new SubjectClass("AERODYNAMICS - I"));
            subjectClasses.add(new SubjectClass("AEROSPACE MATERIALS AND COMPOSITES"));
            subjectClasses.add(new SubjectClass("AEROSPACE PROPULSION - II"));
            subjectClasses.add(new SubjectClass("AEROSPACE VEHICLE STRUCTURES - II"));
            subjectClasses.add(new SubjectClass("AIRCRAFT PRODUCTION TECHNOLOGY"));
            subjectClasses.add(new SubjectClass("ANALOG COMMUNICATIONS"));
            subjectClasses.add(new SubjectClass("ANALYTICAL INSTRUMENTATION"));
            subjectClasses.add(new SubjectClass("AUTOMOTIVE CHASSIS & SUSPENSION"));
            subjectClasses.add(new SubjectClass("AUTOMOTIVE CHASSIS and SUSPENSION"));
            subjectClasses.add(new SubjectClass("AUTOMOTIVE ELECTRICAL AND AUTOTRONICS"));
            subjectClasses.add(new SubjectClass("AUTOMOTIVE ENGINES"));
            subjectClasses.add(new SubjectClass("BASIC ELECTRICAL AND ELECTRONICS"));
            subjectClasses.add(new SubjectClass("BASIC ELECTRONICS AND DEVICES"));
            subjectClasses.add(new SubjectClass("BIO MEDICAL SIGNAL PROCESSING"));
            subjectClasses.add(new SubjectClass("BIOCHEMICAL ENGINEERING"));
            subjectClasses.add(new SubjectClass("BIOCHEMICAL REACTION ENGINEERING-II"));
            subjectClasses.add(new SubjectClass("BIOINFORMATICS"));
            subjectClasses.add(new SubjectClass("BIOLOGICAL CONTROL SYSTEMS"));
            subjectClasses.add(new SubjectClass("BIOMEDICAL INSTRUMENTATION"));
            subjectClasses.add(new SubjectClass("BUILDING MATERIALS AND CONSTRUCTION"));
            subjectClasses.add(new SubjectClass("Biochemical Engineering"));
            subjectClasses.add(new SubjectClass("C PROGRAMMING"));
            subjectClasses.add(new SubjectClass("CHEMICAL ENGINEERING THERMODYNAMICS-I"));
            subjectClasses.add(new SubjectClass("CHEMICAL PROCESS CALCULATIONS"));
            subjectClasses.add(new SubjectClass("CHEMICAL REACTION ENGINEERING-II"));
            subjectClasses.add(new SubjectClass("COMPLEX VARIABLES"));
            subjectClasses.add(new SubjectClass("COMPLEX VARIABLES AND STATISTICAL METHOD"));
            subjectClasses.add(new SubjectClass("COMPUTER ARCHITECTURE"));
            subjectClasses.add(new SubjectClass("COMPUTER NETWORKS"));
            subjectClasses.add(new SubjectClass("COMPUTER ORGANIZATION"));
            subjectClasses.add(new SubjectClass("COMPUTER PROGRAMMING"));
            subjectClasses.add(new SubjectClass("CONCRETE TECHNOLOGY"));
            subjectClasses.add(new SubjectClass("CONTROL SYSTEMS"));
            subjectClasses.add(new SubjectClass("CRYPTOGRAPHY AND NETWORK"));
            subjectClasses.add(new SubjectClass("DATA ACQUISITION SYSTEMS"));
            subjectClasses.add(new SubjectClass("DATA BASE MANAGEMENT SYSTEMS"));
            subjectClasses.add(new SubjectClass("DATA STRUCTURES"));
            subjectClasses.add(new SubjectClass("DATA WARE HOUSING AND DATA MINING"));
            subjectClasses.add(new SubjectClass("DBMS"));
            subjectClasses.add(new SubjectClass("DESIGN & DRAWING OF STEEL STRUCTURES"));
            subjectClasses.add(new SubjectClass("DESIGN AND ANALYSIS OF ALGORITHMS"));
            subjectClasses.add(new SubjectClass("DESIGN OF MACHINE MEMEBERS-II"));
            subjectClasses.add(new SubjectClass("DEVELOPMENT OF MINERAL DEPOSITS"));
            subjectClasses.add(new SubjectClass("DIGITAL IMAGE PROCESSING"));
            subjectClasses.add(new SubjectClass("DIGITAL LOGIC DESIGN"));
            subjectClasses.add(new SubjectClass("DIGITAL SIGNAL PROCESSING"));
            subjectClasses.add(new SubjectClass("DISASTER MANAGEMENT"));
            subjectClasses.add(new SubjectClass("ELECTRICAL CIRCUITS ANALYSIS-I"));
            subjectClasses.add(new SubjectClass("ELECTRICAL DISTRIBUTION SYSTEMS"));
            subjectClasses.add(new SubjectClass("ELECTRICAL MACHINE DESIGN"));
            subjectClasses.add(new SubjectClass("ELECTRICAL MACHINES-I"));
            subjectClasses.add(new SubjectClass("ELECTRICAL MACHINES-II"));
            subjectClasses.add(new SubjectClass("ELECTRICAL SYSTEMS"));
            subjectClasses.add(new SubjectClass("ELECTRICAL TECHNOLOGY"));
            subjectClasses.add(new SubjectClass("ELECTRO MAGENETIC FIELDS"));
            subjectClasses.add(new SubjectClass("ELECTRONIC CIRCUIT ANALYSIS"));
            subjectClasses.add(new SubjectClass("ELECTRONIC DEVICES AND CIRCUITS"));
            subjectClasses.add(new SubjectClass("ELEMENTS OF MECHANICAL ENGINEERING"));
            subjectClasses.add(new SubjectClass("EM WAVES AND TRANSMISSION LINES"));
            subjectClasses.add(new SubjectClass("EMBEDDED SYSTEMS"));
            subjectClasses.add(new SubjectClass("ENGG CHEMISTRY"));
            subjectClasses.add(new SubjectClass("ENGG MECHANICS "));
            subjectClasses.add(new SubjectClass("ENGG PHYSICS"));
            subjectClasses.add(new SubjectClass("ENGINEERING CHEMISTRY"));
            subjectClasses.add(new SubjectClass("ENGLISH-I"));
            subjectClasses.add(new SubjectClass("ENGLISH-II"));
            subjectClasses.add(new SubjectClass("ENVIRONMENTAL ENGINEERING"));
            subjectClasses.add(new SubjectClass("ENVIRONMENTAL STUDIES"));
            subjectClasses.add(new SubjectClass("Electrical Circuit Analysis-II"));
            subjectClasses.add(new SubjectClass("Electronics"));
            subjectClasses.add(new SubjectClass("FARM POWER AND TRACTOR SYSTEMS"));
            subjectClasses.add(new SubjectClass("FLIGHT MECHANICS - II"));
            subjectClasses.add(new SubjectClass("FLIGHT VEHICLE DESIGN"));
            subjectClasses.add(new SubjectClass("FLUID MECHANICS & HYDRAULIC MACHINERY"));
            subjectClasses.add(new SubjectClass("FLUID MECHANICS AND OPEN CHANNEL HYDRAULICS"));
            subjectClasses.add(new SubjectClass("FORMAL LANGUAGES AND AUTOMATA THEORY"));
            subjectClasses.add(new SubjectClass("Fluid Mechanics"));
            subjectClasses.add(new SubjectClass("GENERAL GEOLOGY"));
            subjectClasses.add(new SubjectClass("GEOTECHNICAL ENGINEERING - I"));
            subjectClasses.add(new SubjectClass("GEOTECHNICAL ENGINEERING-II"));
            subjectClasses.add(new SubjectClass("GROUND IMPROVEMENT TECHNNIQUES"));
            subjectClasses.add(new SubjectClass("GROUND WATER HYDROLOGY"));
            subjectClasses.add(new SubjectClass("HEAT AND MASS TRANSFER"));
            subjectClasses.add(new SubjectClass("HEAT TRANSFER"));
            subjectClasses.add(new SubjectClass("HIGH VOLTAGE ENGINEERING"));
            subjectClasses.add(new SubjectClass("HYDRAULICS AND HYDRAULIC MACHINERY"));
            subjectClasses.add(new SubjectClass("IC ENGINES & GAS TURBINES"));
            subjectClasses.add(new SubjectClass("IMMUNOLOGY"));
            subjectClasses.add(new SubjectClass("INDUSTRIAL ENGG & MANAGEMENT"));
            subjectClasses.add(new SubjectClass("INDUSTRIAL ENGG and MANAGEMENT"));
            subjectClasses.add(new SubjectClass("INDUSTRIAL MANAGEMENT"));
            subjectClasses.add(new SubjectClass("INORGANIC CHEMICAL TECHNOLOGY"));
            subjectClasses.add(new SubjectClass("INSTRUMENTATION"));
            subjectClasses.add(new SubjectClass("INSTRUMENTATION & CONTROL SYSTEMS"));
            subjectClasses.add(new SubjectClass("INSTRUMENTATION AND BIO PROCESS CONTROL"));
            subjectClasses.add(new SubjectClass("INSTRUMENTATION and CONTROL SYSTEMS"));
            subjectClasses.add(new SubjectClass("INTRODUCTION TO SPACE TECHNOLOGY"));
            subjectClasses.add(new SubjectClass("JAVA PROGRAMMING"));
            subjectClasses.add(new SubjectClass("KINEMATICS OF MACHINERY"));
            subjectClasses.add(new SubjectClass("LASERS AND FIBER OPTICS IN MEDICINE"));
            subjectClasses.add(new SubjectClass("MACHINE TOOLS & METROLOGY"));
            subjectClasses.add(new SubjectClass("MACHINE TOOLS and METROLOGY"));
            subjectClasses.add(new SubjectClass("MANAGEMENT SCIENCE"));
            subjectClasses.add(new SubjectClass("MANAGERIAL ECONOMICS & FINANCIAL ANALYSIS"));
            subjectClasses.add(new SubjectClass("MANAGERIAL ECONOMICS AND FINANCIAL ANALYSIS"));
            subjectClasses.add(new SubjectClass("MASS TRANSFER OPERATIONS - II"));
            subjectClasses.add(new SubjectClass("MATERIAL ENGINEERING"));
            subjectClasses.add(new SubjectClass("MATHEMATICAL FOUNDATIONS OF COMPUTER SCIENCE"));
            subjectClasses.add(new SubjectClass("MATHEMATICS-I"));
            subjectClasses.add(new SubjectClass("MATHEMATICS-II"));
            subjectClasses.add(new SubjectClass("MATHEMATICS-II (MM)"));
            subjectClasses.add(new SubjectClass("MATHEMATICS-III"));
            subjectClasses.add(new SubjectClass("MBA"));
            subjectClasses.add(new SubjectClass("MECHANICAL UNIT OPERATIONS"));
            subjectClasses.add(new SubjectClass("MECHANICS OF FLUIDS"));
            subjectClasses.add(new SubjectClass("MECHANICS OF SOLIDS"));
            subjectClasses.add(new SubjectClass("MECHANISMS AND MECHANICAL DESIGN"));
            subjectClasses.add(new SubjectClass("MEDICAL IMAGING TECHNIQUES"));
            subjectClasses.add(new SubjectClass("MEMS"));
            subjectClasses.add(new SubjectClass("METALLURGY & MATERIALS SCIENCE"));
            subjectClasses.add(new SubjectClass("METROLOGY"));
            subjectClasses.add(new SubjectClass("MICROPROCESSORS & MICROCONTROLLERS"));
            subjectClasses.add(new SubjectClass("MICROPROCESSORS AND MICROCONTROLLERS"));
            subjectClasses.add(new SubjectClass("MICROWAVE ENGINEERING"));
            subjectClasses.add(new SubjectClass("MINE ENVIRONMENT ENGINEERING - II"));
            subjectClasses.add(new SubjectClass("MINE STYSTEMS ENGINEERING"));
            subjectClasses.add(new SubjectClass("MINE SURVEYING -I"));
            subjectClasses.add(new SubjectClass("MINERAL ENGINEERING AND FUEL TECHNOLOGY"));
            subjectClasses.add(new SubjectClass("MINING GEOLOGY - II"));
            subjectClasses.add(new SubjectClass("MINING GEOLOGY- I"));
            subjectClasses.add(new SubjectClass("MINING MACHINERY"));
            subjectClasses.add(new SubjectClass("MOBILE COMPUTING"));
            subjectClasses.add(new SubjectClass("MOMENTUM TRANSFER"));
            subjectClasses.add(new SubjectClass("Metallurgy"));
            subjectClasses.add(new SubjectClass("Metallurgy & Materials Science"));
            subjectClasses.add(new SubjectClass("Mining Technology"));
            subjectClasses.add(new SubjectClass("NATURAL GAS ENGINEERING"));
            subjectClasses.add(new SubjectClass("NETWORK ANALYSIS"));
            subjectClasses.add(new SubjectClass("OBJECT ORIENTED ANALYSIS AND DESIGN"));
            subjectClasses.add(new SubjectClass("OBJECT ORIENTED PROGRAMMING"));
            subjectClasses.add(new SubjectClass("OOPS THROUGH C++"));
            subjectClasses.add(new SubjectClass("OPEN SORUCE SOFTWARE"));
            subjectClasses.add(new SubjectClass("OPERATING SYSTEMS"));
            subjectClasses.add(new SubjectClass("OPTICAL COMMUNICATIONS"));
            subjectClasses.add(new SubjectClass("ORGANIC CHEMISTRY"));
            subjectClasses.add(new SubjectClass("Operations Research"));
            subjectClasses.add(new SubjectClass("P AND S"));
            subjectClasses.add(new SubjectClass("PETROLEUM GEOLOGY"));
            subjectClasses.add(new SubjectClass("PETROLEUM INDUSTRY MANAGEMENT"));
            subjectClasses.add(new SubjectClass("PETROLEUM PRODUCTION ENGINEERING"));
            subjectClasses.add(new SubjectClass("PETROLEUM RESERVOIR ENGINEERING"));
            subjectClasses.add(new SubjectClass("PHYSICAL CHEMISTRY"));
            subjectClasses.add(new SubjectClass("PHYSICAL METALLURGY"));
            subjectClasses.add(new SubjectClass("POWER SEMICONDUCTOR DRIVES"));
            subjectClasses.add(new SubjectClass("POWER SYSTEM ANALYSIS"));
            subjectClasses.add(new SubjectClass("POWER SYSTEM OPERATION and CONTROL"));
            subjectClasses.add(new SubjectClass("POWER SYSTEMS-I"));
            subjectClasses.add(new SubjectClass("PRINCIPLES OF COMMUNICATION"));
            subjectClasses.add(new SubjectClass("PRINCIPLES OF SOIL SCIENCE AND AGRONOMY"));
            subjectClasses.add(new SubjectClass("PROBABILITY AND STATISTICS"));
            subjectClasses.add(new SubjectClass("PROCESS DYNAMICS & CONTROL"));
            subjectClasses.add(new SubjectClass("PROCESS DYNAMICS and CONTROL"));
            subjectClasses.add(new SubjectClass("PROCESS ENGINEERING ECONOMICS"));
            subjectClasses.add(new SubjectClass("PROCESS HEAT TRANSFER"));
            subjectClasses.add(new SubjectClass("PRODUCT DESIGN AND ASSEMBLY AUTOMATION"));
            subjectClasses.add(new SubjectClass("PRODUCTION TECHNOLOGY"));
            subjectClasses.add(new SubjectClass("PROFESSIONAL ETHICS and HUMAN VALUES"));
            subjectClasses.add(new SubjectClass("PROPERTIES AND STRENGTH OF MATERIALS"));
            subjectClasses.add(new SubjectClass("PULSE & DIGITAL CIRCUITS"));
            subjectClasses.add(new SubjectClass("Petroleum Engineering"));
            subjectClasses.add(new SubjectClass("Professional Ethics and Human Values"));
            subjectClasses.add(new SubjectClass("RADAR SYSTEMS"));
            subjectClasses.add(new SubjectClass("RANDOM VARIABLES and STOCHASTIC PROCESSES"));
            subjectClasses.add(new SubjectClass("REFRIGERATION "));
            subjectClasses.add(new SubjectClass("REMOTE SENSING AND GIS APPLICATION"));
            subjectClasses.add(new SubjectClass("RENEWABLE ENERGY SOURCES"));
            subjectClasses.add(new SubjectClass("ROBOTICS"));
            subjectClasses.add(new SubjectClass("SIGNAL CONDITIONING"));
            subjectClasses.add(new SubjectClass("SOFTWARE ENGINEERING"));
            subjectClasses.add(new SubjectClass("SOFTWARE PROJECT MANAGEMENT"));
            subjectClasses.add(new SubjectClass("SOIL MECHANICS"));
            subjectClasses.add(new SubjectClass("STRENGTH OF MATERIALS"));
            subjectClasses.add(new SubjectClass("STRENGTH OF MATERIALS- II"));
            subjectClasses.add(new SubjectClass("STRUCTURAL ANALYSIS"));
            subjectClasses.add(new SubjectClass("STRUCTURE AND ORGANIZATION OF TISSUES"));
            subjectClasses.add(new SubjectClass("SURFACE MINING"));
            subjectClasses.add(new SubjectClass("SURFACE PRODUCTION OPERATIONS"));
            subjectClasses.add(new SubjectClass("SURFACE WATER HYDROLOGY"));
            subjectClasses.add(new SubjectClass("SURVEYING"));
            subjectClasses.add(new SubjectClass("SURVEYING AND OFFSHORE STRUCTURES"));
            subjectClasses.add(new SubjectClass("SWITCH GEAR & PROTECTION"));
            subjectClasses.add(new SubjectClass("SWITCHING THEORY AND LOGIC DESIGN"));
            subjectClasses.add(new SubjectClass("SYSTEM MODELING AND SIMULATION"));
            subjectClasses.add(new SubjectClass("TELECOMMUNICATION SWITCHING SYSTEMS"));
            subjectClasses.add(new SubjectClass("THEORY OF MACHINES"));
            subjectClasses.add(new SubjectClass("THERMAL ENGINEERING -I"));
            subjectClasses.add(new SubjectClass("THERMAL ENGINEERING FOR MINING"));
            subjectClasses.add(new SubjectClass("THERMODYNAMICS"));
            subjectClasses.add(new SubjectClass("THERMODYNAMICS & KINETICS"));
            subjectClasses.add(new SubjectClass("THERMODYNAMICS FOR PETROLEUM ENGINEERS"));
            subjectClasses.add(new SubjectClass("TRANSDUCER TECHNOLOGY"));
            subjectClasses.add(new SubjectClass("TRANSPORT PHENOMENA IN BIO PROCESSES"));
            subjectClasses.add(new SubjectClass("TRANSPORTATION ENGINEERING - II"));
            subjectClasses.add(new SubjectClass("Thermal & Hydro Prime Movers"));
            subjectClasses.add(new SubjectClass("UML & DESIGN PATTERNS"));
            subjectClasses.add(new SubjectClass("UNCONVENTIONAL MACHINING PROCESSES"));
            subjectClasses.add(new SubjectClass("UNDER GROUND METAL MINING TECHNOLOGY"));
            subjectClasses.add(new SubjectClass("UNIX PROGRAMMING"));
            subjectClasses.add(new SubjectClass("UTILIZATION OF ELECTRICAL ENERGY"));
            subjectClasses.add(new SubjectClass("VEHICLE TRANSPORT MANAGEMENT"));
            subjectClasses.add(new SubjectClass("VLSI DESIGN"));
            subjectClasses.add(new SubjectClass("WATER AND WASTEWATER ENGINEERING"));
            subjectClasses.add(new SubjectClass("WATER RESOURCES ENGINEERING - II"));
            subjectClasses.add(new SubjectClass("WELL COMPLETIONS & TESTING"));
            subjectClasses.add(new SubjectClass("WELL COMPLETIONS and TESTING"));
            mProgressDialog.dismiss();
            gridViewAdapter = new GridViewAdapter(RRBExamsActivity.this,subjectClasses);
            gridView.setAdapter(gridViewAdapter);
            sv.setQueryHint("Select Subject");
            sv.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
                @Override
                public boolean onQueryTextSubmit(String query) {
                    return false;
                }

                @Override
                public boolean onQueryTextChange(String newText) {
                    //SEARCH FILTER
                    gridViewAdapter.filter(newText);
                    return false;
                }
            });
            gridView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                    final String type = ((TextView)view.findViewById(R.id.textView)).getText().toString();

                    final AlertDialog.Builder builder = new AlertDialog.Builder(RRBExamsActivity.this);
                    LayoutInflater inflater = RRBExamsActivity.this.getLayoutInflater();
                    final View dialogView = inflater.inflate(R.layout.modeofexam, null);
                    builder.setView(dialogView);
                    alertDialog = builder.create();
                    alertDialog.show();
                    Button practice = (Button)dialogView.findViewById(R.id.practice);
                    practice.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View v) {
                            mode = "practice";
                            editor = settings.edit();
                            editor.putString("exammode",mode);
                            editor.commit();
                            Intent intent1 = new Intent(RRBExamsActivity.this,Quiz.class);
                            intent1.putExtra("subname",type);
                            startActivity(intent1);
                            alertDialog.dismiss();
                        }
                    });
                    Button test =(Button)dialogView.findViewById(R.id.test);
                    test.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View v) {
                            mode = "test";
                            editor = settings.edit();
                            editor.putString("exammode",mode);
                            editor.commit();
                            Intent intent1 = new Intent(RRBExamsActivity.this,Quiz.class);
                            intent1.putExtra("subname",type);
                            startActivity(intent1);
                            alertDialog.dismiss();
                        }
                    });
                }
            });
        }

    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()){
            case android.R.id.home:
                this.finish();
                break;
        }
        return super.onOptionsItemSelected(item);
    }
    private boolean isNetworkAvailable() {
        ConnectivityManager connectivityManager
                = (ConnectivityManager) getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkInfo activeNetworkInfo = connectivityManager.getActiveNetworkInfo();
        return activeNetworkInfo != null && activeNetworkInfo.isConnected();
    }
}
